### PR TITLE
rewrite to use rio for imports

### PR DESCRIPTION
**Pull request by leeper**
This is a quite substantial rewrite that (mostly) relies on rio to handle the import functionality. I've tried to simplify a lot of aspects of the code internals (given that rio will take care of most of the file handling aspects), trim down the interface a bit, and make the display of options more reactive.

It would be possible to dynamically add options for additional file types (e.g., overriding the default separators for delimited files, allowing `stringsAsFactors = TRUE`, selecting objects from an .Rdata file, etc.) but I haven't implemented any of that.

### CODE REVIEW

**Comment by Stan125** [comment]
Hi Thomas,

thank you very much for your Pull Request. I used your version of the Add-In for a while, and noticed several things:
1. You removed the option to specify column and decimal separators, therefore making a few files of mine unable to read. I often deal with a comma separator, this is crucial.
2. The `obtain_filetype()` function is now redundant. I like this suggestion.
3. The dataset name is now redundant. I like this suggestion.
4. You deleted a lot of comments.
5. The Add-In is now in the viewer pane. This is personal taste, I'd rather have a window for that.
6. `GREA_read()` now uses the `structure()` function. 

Could you explain 1. and 6.?

All the Best,
Stani

**Comment by leeper** [comment]
Hi Stani,

Thanks for your response. I've just pushed an update to address some of this.
- Regarding (1), I've exposed `header`, `sep`, and `sep2` (or `dec`) arguments for delimited files. These options are displayed in the UI when a text file is used. It would be possible to add arguments for other file types, so I'm happy to add that if you'd like.
- Regarding (4), I added back some comments to clarify behavior.
- Regarding (5), I've restored the use of a window for the viewer.
- Regarding (6), this is a trivial change. All it does is store the `import()` command in an attribute so that it is easier to paste into the console. `structure()` is just a convenient way of adding attributes to an object. It does not change the basic dataframe structure.

Best,
-Thomas

**Comment by Stan125** [comment]
Hi Thomas,

thank you for your update and clarification. By going through your code I have learned quite a lot.
I have some remarks:
1. The column separator does not work. I am still unable to read some of my .csv files.
2. I liked the original layout of the Add-In better.

As I really like some of your improvements, but am not completely happy with other changes, I would like to take parts of your Pull Request and implement it, while leaving other parts untouched. E.g., I would still like to use `read.table()` for reading .csv files. I hope that's alright. 

One more question: You seem to have solved #11. Do you know why?

All the Best,
Stani

**Comment by leeper** [comment]
It's your package, so you should do whatever you think is best. Let me know if you'd like me to make any of your preferred changes as part of this PR.

In terms of #11, I believe the answer is in: setting `stopOnCancel = TRUE` in `runGadget(app, viewer = viewer, stopOnCancel = TRUE)`.

**Comment by Stan125** [comment]
Thanks! When starting up your version of GREA, I was able to replicate #11. The mystery remains ;-).

I actually found out the reason why I was not able to correctly read my `.csv` file via `import()`. I believe it has something to do with your `import_delim()` function. Will send you a PR soon.

**Comment by leeper** [comment]
Makes sense. I just noticed a problem in this the other day, so possibly reinstall rio from GitHub. I'll be pushing an update to CRAN this week.

**Comment by Stan125** [comment]
Yup, all works now! And here I was sitting putting together a PR ;)

**Comment by leeper** [comment]
Great! Do you want me to update so the options are displayed in two columns, again?

**Comment by Stan125** [comment]
Thank you, but I still have to take time to learn your code. I will implement part by part so I still have an overview on how the Add-In works.

**Comment by Stan125** [comment]
Hi Thomas,

I now integrated most of your work into the Add-In. The only two things I left untouched were 1. your changes to the `wd_check()` function, because it had the ability paste the filepath without the WD even if a file lays in a subfolder of your working directory. And 2. I only used `rio` to import non-text files, because it cannot deal with the decimal comma separator. Once https://github.com/leeper/rio/issues/106 is resolved I will update it.

I learned a lot while reading your code (giving a function an attribute where the call itself is saved is pretty smart!) and especially the UI code is now highly improved. Thank you again for your work. 

All the Best,
Stani

**Pull request merged**
